### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by BioPhoton** [dskgry/nodejs-workshop#3]
To make it more clear you should add several things to your readme.md

- [ ] note the required versions and softwares (node, rethinkdb)
- [ ] describe how somebody could check the node version `node --version`
- [ ] add `cd server` as first task before `start any rethink db`
- [ ] add `cd app` as first task before `npm install` 
- [ ] replace the bullet list with a numbered list
- [ ] add the link to the [slides](https://speakerdeck.com/manuelrauber/modern-web-apis-with-node-dot-js-2)

**Comment by dskgry** [comment]
Thanks for your feedback. I improved the docs :)

**Comment by BioPhoton** [comment]
Cool!
