### ISSUE TITLE
Object.assign() mutation because of missing empty object

### ISSUE THREAD

**Issue by NehrDani** [dskgry/nodejs-workshop#5]
**Branch: 05_post_validation**
File: `server/tweets/tweetService.js`

On the method `createTweet` you are missing the initial empty object when using `Object.assign()`. This leads to mutating the original object.

```js
const notMutated = Object.assign({}, foo, { bar: 'baz' })
```

**Comment by dskgry** [comment]
Fixed :)
Thanks you again
